# === Blur & Shadows ===
blur = 1
shadows = 0

# === Window Visuals ===
borderpx = 4
border_radius = 8
no_radius_when_single = 0
focused_opacity = 1.0
unfocused_opacity = 0.96

# Window Separation
gappih = 4
gappiv = 4
gappoh = 8
gappov = 8

# === Animations ===
animations = 1

# Animation for switching tags
tag_animation_direction = 0
animation_duration_tag = 300
animation_curve_tag= 0.46, 1.0, 0.29, 1

# Animation for opening windows
animation_type_open = zoom
zoom_initial_ratio = 0.2
animation_duration_open = 400
animation_curve_open = 0.46, 1.0, 0.29, 1

# Animation for closing windows
animation_type_close = fade
fadeout_begin_opacity = 1.0
animation_duration_close = 200
animation_curve_close = 0.46, 1.0, 0.29, 1
